kind: ConfigMap
apiVersion: v1
metadata:
  name: example-vs
  namespace: f5demo
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
  {
  "virtualServer": {
    "backend": {
      "serviceName": "example-vs-iapp",
      "servicePort": 80
    },
    "frontend": {
      "partition": "ose",
      "iapp": "/Common/f5.http",
      "iappPoolMemberTable": {
        "name": "pool__members", 
        "columns": [
            {"name": "addr", "kind": "IPAddress"},
            {"name": "port", "kind": "Port"},
            {"name": "connection_limit", "value": "0"}
        ]
      },
      "iappOptions": {
        "description": "Example iApp"
      },
      "iappVariables": {
        "monitor__monitor": "/#create_new#",
        "monitor__response": "none",
        "monitor__uri": "/",
        "net__client_mode": "wan",
        "net__server_mode": "lan",
        "pool__addr": "127.0.0.2",
        "pool__pool_to_use": "/#create_new#",
        "pool__port": "8080"
      }
    }
  }
  }
