kind: ConfigMap
apiVersion: v1
metadata:
  name: example-vs
  namespace: f5demo
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "frontend": {
          "balance": "round-robin",
          "mode": "http",
          "partition": "ose",
          "virtualAddress": {
            "bindAddr": "10.1.2.50",
            "port": 443
          },
          "sslProfile": {
            "f5ProfileName": "Common/clientssl"
          }
        },
        "backend": {
          "serviceName": "f5-hello-world",
          "servicePort": 8080
        }
      }
    }
