apiVersion: v1
kind: ConfigMap
metadata:
  name: f5-hello-world-ssl
  namespace: f5demo
  labels:
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  data: |
    {
      "virtualServer": {
        "frontend": {
          "balance": "round-robin",
          "mode": "http",
          "partition": "ose",
          "virtualAddress": {
            "bindAddr": "10.1.2.50",
            "port": 443
          },
          "sourceAddressTranslation": {
            "type": "automap"
          }
        },
        "backend": {
          "serviceName": "f5-hello-world",
          "servicePort": 8080,
          "healthMonitors": [ {
            "send": "GET / HTTP/1.0\\r\\n\\r\\n",
            "interval": 30,
            "timeout": 20,
            "protocol": "http"
            }
          ]
        }
      }
    }
