apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bigip01-ctlr
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      name: k8s-bigip-ctlr1
      labels:
        app: k8s-bigip-ctlr1
    spec:
      serviceAccountName: k8s-bigip-ctlr
      containers:
        - name: k8s-bigip-ctlr
          image: "f5networks/k8s-bigip-ctlr:latest"
          env:
          - name: BIGIP_USERNAME
            valueFrom:
             secretKeyRef:
              name: bigip-login
              key: username
          - name: BIGIP_PASSWORD
            valueFrom:
             secretKeyRef:
              name: bigip-login
              key: password
          command: ["/app/bin/k8s-bigip-ctlr"]
          args: [
             "--bigip-username=$(BIGIP_USERNAME)",
             "--bigip-password=$(BIGIP_PASSWORD)",
             "--bigip-url=10.1.3.100",
             "--bigip-partition=ose",
             "--namespace=tenanta-dev",
             "--pool-member-type=cluster",
             "--openshift-sdn-name=/Common/ose-tunnel",
             "--insecure=true"
          ]
      imagePullSecrets:
        - name: f5-docker-images
